// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxn8mOKFDea_pIs7QQumMCGQk9NV39r9Y',
    appId: '1:735158512346:web:226cd6a013aacb043593e3',
    messagingSenderId: '735158512346',
    projectId: 'zirel-pos-app',
    authDomain: 'zirel-pos-app.firebaseapp.com',
    storageBucket: 'zirel-pos-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8QtdnZfy9PdOqEJmEKPbmkf-PPCwTogA',
    appId: '1:735158512346:android:6962451a06968f603593e3',
    messagingSenderId: '735158512346',
    projectId: 'zirel-pos-app',
    storageBucket: 'zirel-pos-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0bZ2U3KN3ZK0pvrTNM97iEGMUWoEgm64',
    appId: '1:735158512346:ios:a0f67e3dd14b16673593e3',
    messagingSenderId: '735158512346',
    projectId: 'zirel-pos-app',
    storageBucket: 'zirel-pos-app.firebasestorage.app',
    androidClientId: '735158512346-hor070fqhtd81k0obeih5nia7mbud27b.apps.googleusercontent.com',
    iosClientId: '735158512346-cf0kcnrkjerj4aq1o8mgqr9kk478e826.apps.googleusercontent.com',
    iosBundleId: 'elriztechnology.com.flutterPos',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0bZ2U3KN3ZK0pvrTNM97iEGMUWoEgm64',
    appId: '1:735158512346:ios:a0f67e3dd14b16673593e3',
    messagingSenderId: '735158512346',
    projectId: 'zirel-pos-app',
    storageBucket: 'zirel-pos-app.firebasestorage.app',
    androidClientId: '735158512346-hor070fqhtd81k0obeih5nia7mbud27b.apps.googleusercontent.com',
    iosClientId: '735158512346-cf0kcnrkjerj4aq1o8mgqr9kk478e826.apps.googleusercontent.com',
    iosBundleId: 'elriztechnology.com.flutterPos',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkTI6SME6YjVEUYVS7hCqHlyhuAuQVNYk',
    appId: '1:406037321591:web:9a7106a4a52f5ff2a3b372',
    messagingSenderId: '406037321591',
    projectId: 'flutter-pos-478ed',
    authDomain: 'flutter-pos-478ed.firebaseapp.com',
    storageBucket: 'flutter-pos-478ed.appspot.com',
  );
}
